# Generated by Django 4.0.3 on 2023-06-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_rename_automobile_sale_automobile_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Automobile_VIN',
            new_name='automobile',
        ),
    ]
