# Generated by Django 4.0.3 on 2023-06-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0009_alter_automobilevo_import_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.PositiveBigIntegerField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutomobileVO', to='sales_rest.automobilevo'),
        ),
    ]
