# Generated by Django 4.0.3 on 2023-06-09 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0011_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='automobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AutombileVO', to='sales_rest.automobilevo'),
        ),
    ]
