<<<<<<< HEAD
# Generated by Django 4.0.3 on 2023-06-06 18:26
=======
# Generated by Django 4.0.3 on 2023-04-28 18:26
>>>>>>> refs/remotes/Master/main

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('import_href', models.CharField(max_length=100, null=True, unique=True)),
                ('vin', models.CharField(max_length=17)),
                ('sold', models.BooleanField()),
=======
                ('import_href', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('sold', models.BooleanField(default=False)),
>>>>>>> refs/remotes/Master/main
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
<<<<<<< HEAD
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
=======
                ('last_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
>>>>>>> refs/remotes/Master/main
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('date_time', models.DateField(null=True)),
                ('reason', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('vin', models.CharField(max_length=17)),
                ('customer', models.CharField(max_length=100)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician', to='service_rest.technician')),
=======
                ('status', models.CharField(choices=[('Finished', 'Finished'), ('Canceled', 'Canceled'), ('Created', 'Created')], default='Created', max_length=40)),
                ('vin', models.CharField(max_length=17)),
                ('date_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('is_vip', models.BooleanField(default=False)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_rest.technician')),
>>>>>>> refs/remotes/Master/main
            ],
        ),
    ]
