# Generated by Django 4.0.3 on 2023-06-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_appointment_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('finished', 'Finished'), ('cancelled', 'Canceled')], default='current', max_length=100),
        ),
    ]
